name: Build Android Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies with bun
        run: |
          bun install

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: masth
          path: android/app/build/outputs/apk/release/
    
      - name: Bundle Apk
        run: |
          cd android && ./gradlew bundleRelease
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: masth-bundle
          path: android/app/build/outputs/bundle/release/
